name: Periodic NVD Scan

on:
  schedule:
    - cron: '0 8 * * 1-5' # Every weekday at 8:00 AM

jobs:
  nvd-scan:
    uses: yetanalytics/workflow-nvd/.github/workflows/nvd-scan.yml@v1
    with:
      nvd-clojure-version: '3.2.0'
      classpath-command: 'clojure -Spath -A:cli:server'
      nvd-config-filename: '.nvd/config.json'
      notify-slack: true
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
